### ISSUE TITLE
Can't build on windows

### ISSUE THREAD

**Issue by vcvrackideas** [Xenakios/Atelier#1]
Hi! First - thank you guys! Such a wonderful work here. But can't build it on windows - Makefile:37: ../Rack-SDK/plugin.mk: No such file or directory

**Comment by Xenakios** [comment]
Did you use "make" with the RACK_DIR location set correctly? Anyway, there will be binaries available soon also.

**Comment by vcvrackideas** [comment]
I usually do "make install" and everything is ok with bunch of modules I built before. But maybe it's something different in makefile here EDIT - Yeah! Just changed RACK_DIR like ..\.. - thanks!
