### ISSUE TITLE
Palette:Polyphonic trigger input triggers all the voices on every trigger

### ISSUE THREAD

**Issue by nnbveh** [Xenakios/Atelier#14]
Hi. So I've combined three triggers from the uGraph sequencer and sending them to the Palette, but it just triggers all the voices all the time, this is not the case with your own macro polyoscillator so I'll assume it's a bug...
<img width="1172" alt="Screen Shot 2021-07-05 at 14 22 33" src="https://user-images.githubusercontent.com/39271290/124441147-97241a00-dda5-11eb-8047-cf4ca05114bb.png">

on the screenshot you can see I have 16 voice polyphony and they all are triggered by only 3 channels worth of triggers, looks wrong to me. If I set palette to 3 voice polyphony it's still the same.

**Comment by xandramax** [comment]
Turn the Unison knob (at the top left of the panel) all the way down. This knob is for triggering up to sixteen voices using a monophonic trigger/CV.

**Comment by nnbveh** [comment]
Ah, i was so happy that the only grip i have with polyoscillator was solved, the need to supply v/octave in order to make it polyphonic, but i was wrong, that's not what that knob is for...Could you maybe add an option to detect a number of channels from another cv inputs, like bogaudio modules do? I'm not using this module to play melodic stuff and i have to use some sort of polyphonic constant voltage source just to make it poly...
<img width="359" alt="Screen Shot 2021-07-06 at 10 11 08" src="https://user-images.githubusercontent.com/39271290/124536749-1c153f00-de4b-11eb-982f-728e751cbf3c.png">

**Comment by Xenakios** [comment]
I may look into how the polyphony/unison modes work at some point, but handling all the various use cases that might be desired will probably require quite a lot of new code.
