### ISSUE TITLE
Can't build v2 on windows

### ISSUE THREAD

**Issue by vcvrackideas** [Xenakios/Atelier#15]
Hi! Can't build v2 with latest SDK, no rules for makefile, Thanks

**Comment by SteveRussell33** [comment]
You can build from my fork if you wish, includes the addition of the LFO mode PR.
https://github.com/SteveRussell33/Atelier

**Comment by vcvrackideas** [comment]
> You can build from my fork if you wish, includes the addition of the LFO mode PR. https://github.com/SteveRussell33/Atelier

thank you so much Steve!

**Comment by Xenakios** [comment]
Some build problems are expected at this point. Ensure you are trying to build the v2 branch of this repository with the correct Rack 2 SDK and that you are testing with the corresponding Rack 2 application. Once Rack 2 is officially released, the main branch of this repository will be updated to build for Rack 2.

**Comment by SteveRussell33** [comment]
> 
> 
> > You can build from my fork if you wish, includes the addition of the LFO mode PR. https://github.com/SteveRussell33/Atelier
> 
> thank you so much Steve!

You're welcome!

Although now that Xenakios has added the LFO mode code, you can now build from his v2 branch, and so I have deleted my fork as it's not needed.
