### ISSUE TITLE
Please change GPL-3.0-only license to GPL-3.0-or-later

### ISSUE THREAD

**Issue by falkTX** [Xenakios/Atelier#18]
In the plugin.json (and maybe other places) you state the license of the project as being GPL-3.0-only.
This might be just a side effect from the initial fork of AudibleInstruments, which until April 2020 was GPL-3.0-only.
It was then changed https://github.com/VCVRack/AudibleInstruments/commit/cd3659198c0426cc23100d9f80e1ec29ace6d81e

I am hoping to use your code in another opensource project, but this 3.0-only is a blocker.
There is discussion about this already in https://github.com/zezic/ZZC/issues/86 and https://github.com/MarcBoule/Geodesics/issues/4

Seeing as the original project changed from 3.0-only to 3.0+ I am hoping you can consider doing the same.
Thanks!

**Comment by Xenakios** [comment]
OK, I will finish doing that in the coming days. I already changed the license in the plugin.json file, but I have to go through all the files to see if they mention "GPL3.0 only" and change that to the updated one.

**Comment by falkTX** [comment]
Thank you, that is very appreciated.

**Comment by falkTX** [comment]
Closing, since from what I can see this is all done now.
Thanks again!
