### ISSUE TITLE
Output mix CV input strange behavior

### ISSUE THREAD

**Issue by vcvrackideas** [Xenakios/Atelier#19]
It seems it doesn't work at all, especially when knob is fully on and then attenuverter to fully CCW has been applied. However I clearly hear changes when turn the big control knob itself. Thus seems CV input doesn't make sense yet.

**Comment by Xenakios** [comment]
I can't reproduce that problem here. How is your patch set up? edit : OK, seems it happens when polyphony is activated, only one voice is modulated if the modulation signal is not polyphonic.

**Comment by Xenakios** [comment]
Fixed for v2.0.2
