### ISSUE TITLE
Suggestion: Additional visual cue in Vowel & Speech panel

### ISSUE THREAD

**Issue by xandramax** [Xenakios/Atelier#2]
When using the Vowel & Speech model, the Tune-LPG knob changes function to instead control intonation/prosody (referred to as "intonation" in the manual and "prosody" [in the code](https://github.com/Xenakios/Atelier/blob/cbd969ef935e6daec48ea6c0e832becb08f7816c/eurorack/plaits/dsp/voice.cc#L156)). Also, the VOW-WRD-LPG knob changes to instead control speed.

Maybe the blue LPG icons associated with these knobs should change (even to a different color?) to make this difference clearer without having to consult the manual or find through trial and error. A visual change could lead a user to experiment when they might not discover this functionality otherwise.

![palette](https://user-images.githubusercontent.com/12039110/87214290-3597af80-c2f9-11ea-9ec2-bdd6b6180f5d.PNG)

**Comment by Xenakios** [comment]
I'll mention it to Pyer, but no promises it will be done. (It would of course be consistent with the otherwise dynamically changing panel components...)

**Comment by xandramax** [comment]
Palette's modulation indicators alerted me to something I'd never noticed before, which I've now confirmed is also a part of Audible Instruments Macro Oscillator 2:

The re-assignment of those two knobs (described in the issue above) actually only occurs when the Harmonics knob is turned past 11 o'clock. In other words, when the Palette MODE knob is set to FOR, SAM, or LPC, all LPG knobs do indeed control LPG attenuvertion as the panel presently suggests.

I don't have the actual Plaits hardware to confirm that this is actually how it behaves, but upon reviewing the relevant text in the manual I see that it could be interpreted to be describing this functionality (the text about the knob reassignment comes right after a sentence regarding moving the Harmonics knob past 11 o'clock).

Therefore, if the proposal presented in this issue were to be adopted, the relevant panel icons should only change when both of the following are true:
- The Vowel and Speech engine is selected for polyphony channel 1
- The Harmonics (MODE) knob is set past 11 o'clock (LPC WORDS BANKS)

**Comment by xandramax** [comment]
Further testing reveals that this reassignment also occurs when CV modulation pushes the Harmonics setting past 11 o'clock (even if the knob is "physically" set further to the left). LPG modulation of Morph (VOW-WRD) is progressively attenuated as the Harmonics setting approaches 11 o'clock.

So, then, in order to visualize the function of those knobs on the panel as I suggested, the actual (post-modulation) value of the Harmonics knob must be taken into account.

**Comment by Xenakios** [comment]
Closing for now, some visual indicators for the speech engine mode was done for 2.0.1.
