### ISSUE TITLE
Tag v2.0.2

### ISSUE THREAD

**Issue by cbix** [Xenakios/Atelier#20]
Could you please add a git tag/release for the `v2.0.3` version, if that's the latest stable release? Thanks :)

**Comment by Xenakios** [comment]
The 2.0.3 is not release ready at the moment

**Comment by cbix** [comment]
@Xenakios thanks for your reply, I see. Could you maybe add a tag or v2.0.2 then? I'd like to package this for Arch Linux eventually and having release tags makes things a lot easier :)

**Comment by Xenakios** [comment]
Added the 2.0.2 tag

**Comment by cbix** [comment]
Thanks!
