### ISSUE TITLE
Suggestion: Remove the now-redundant fine-tuning function

### ISSUE THREAD

**Issue by xandramax** [Xenakios/Atelier#4]
In the original Plaits, when the Frequency-CV input is not patched, its attenuverter functions as a fine-tuning knob.

Because Palette adds a large dedicated fine-tuning knob, perhaps this newly-redundant specialized behavior of the Frequency-CV attenuverter should be removed? This would reduce the amount of "hidden functionality", which is consistent with the general theme behind Palette's interface design.

**Comment by Xenakios** [comment]
OK, this _looks_ like it should be easy to handle, but again there's an exception that has to be done because of the speech synthesis engine. (The FM attenuverter acts not as a fine tune but as an intonation curve control when the FM CV input isn't patched in...)

**Comment by xandramax** [comment]
> 
> 
> OK, this _looks_ like it should be easy to handle, but again there's an exception that has to be done because of the speech synthesis engine. (The FM attenuverter acts not as a fine tune but as an intonation curve control when the FM CV input isn't patched in...)

It's the LPG-Frequency attenuverter that acts as intonation control, not the Frequency-CV attenuverter (which is the one with the redundant fine-tuning function).

**Comment by Xenakios** [comment]
> 
> It's the LPG-Frequency attenuverter that acts as intonation control, not the Frequency-CV attenuverter (which is the one with the redundant fine-tuning function).

This was a change you already did then, I think...?

**Comment by xandramax** [comment]
The only change I made in regards to this was to ensure that the (now redundant) fine-tuning function still worked even when the LPG is activated (by patching the trigger input). This was Poly_AudibleInstruments [PR 4](https://github.com/Xenakios/Poly_AudibleInstruments/pull/4).

This suggestion would instead revert that change as well as remove this fine-tuning functionality when Trigger is unpatched.

I've got a working patch which implements this suggestion; I'll submit it as a pull request so you can review.
