### ISSUE TITLE
Bug: Outputs constant voltage for some voices

### ISSUE THREAD

**Issue by gwatcha** [Xenakios/Atelier#9]
Hey, first off let me say thank you for making this, plaits is one of my favorite modules, and you made it so beautiful!

As for the bug, I noticed that some voices output a constant voltage. Here's a video to demonstrate:
https://imgur.com/a/mNesVbm

I'm not sure how I produced the bug. 

When I remove the module and bring it back the constants go away.

**Comment by Xenakios** [comment]
> Hey, first off let me say thank you for making this, plaits is one of my favorite modules, and you made it so beautiful!
> 
> As for the bug, I noticed that some voices output a constant voltage. Here's a video to demonstrate:
> https://imgur.com/a/mNesVbm
> 
> I'm not sure how I produced the bug.
> 
> When I remove the module and bring it back the constants go away.

Yes, I have noticed that problem with the Granular Cloud mode. It might be very difficult to fix because it happens so randomly, but it is probably an uninitialized variable in the code doing it.

**Comment by Xenakios** [comment]
I did some fixes in the code that may have helped these issues, so closing for now, but if the issues keep appearing, post a new issue.
